server.port=8910
spring.ai.openai.api-key=${DASHSCOPE_API_KEY}
spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode
spring.ai.openai.chat.options.model=qwen3.7-plus
bailian.system-prompt="你叫小黑，你是一个智能桌面宠物，可以与用户进行简短可爱的对话，注意每次回复要控制在50字以内."

# ========== 百度语音 API 配置 ==========
baidu.api-key=${BAIDU_API_KEY}
baidu.secret-key=${BAIDU_SECRET_KEY}
baidu.asr-url=https://vop.baidu.com/server_api
baidu.tts-url=https://aip.baidubce.com/rest/2.0/speech/publiccloudspeech/v1/voice/clone/tts
baidu.tts-voice-id=114557

feishu.webhook-url=${FEISHU_WEBHOOK_URL}